{% set name = "prodock" %}
{% set version = "0.1.1b1" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  noarch: python
  entry_points:
    - prodock=prodock.cli:main
  script: |
    {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.11,<3.12
    - pip
    - hatchling

  run:
    - python >=3.11,<3.12
    - rdkit >=2025.03.5
    - prolif >=2.0.3
    - meeko >=0.6.1
    - py3dmol >=2.5.2
    - pandas
    - tqdm
    - matplotlib
    - vina
    - ipywidgets >=8.1.7
    - mdanalysis
    - openbabel >=3.1.1
    - pymol-open-source >=3.1.0
    - pdbfixer
    - openmm ==8.3.1

test:
  requires:
    - pip
  commands:
    - python -c "import prodock; print('prodock import ok')"
    - python -c "import prodock.cli"
    - prodock --help
    - pip check

about:
  home: https://github.com/Medicine-Artificial-Intelligence/ProDock
  summary: "ProDock — automation utilities for molecular docking workflows."
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/Medicine-Artificial-Intelligence/ProDock
  doc_url: https://prodock.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - TieuLongPhan