[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "prodock"
version = "0.5.0"
description = "ProDock — automation utilities for molecular docking workflows."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE"]

authors = [
  { name = "Hoang-Son Lai Le", email = "lelaihoangson@tamu.edu" },
  { name = "Thanh-An Pham", email = "thanh-an.pham@etu.unistra.fr" },
  { name = "Tieu Long Phan", email = "tieu@bioinf.uni-leipzig.de" }
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

keywords = ["docking", "molecular-docking", "bioinformatics", "rdkit", "vina"]

dependencies = [
  "rdkit>=2025.3.5",
  "prolif>=2.0.3",
  "openbabel-wheel==3.1.1.21",
  "meeko>=0.6.1",
  "py3Dmol>=2.5.2",
  "pandas",
  "tqdm",
  "matplotlib",
  "pymol_open_source==3.2.0a0",
  "vina>=1.2.5",
  "ipywidgets>=8.1.7"
]

[project.optional-dependencies]
docs = [
  "sphinx>=7.4,<10",
  "pydata-sphinx-theme>=0.15",
  "sphinxcontrib-bibtex>=2.6"
]

[project.scripts]
prodock = "prodock.cli:main"

[project.urls]
Homepage = "https://github.com/Medicine-Artificial-Intelligence/ProDock"
Source = "https://github.com/Medicine-Artificial-Intelligence/ProDock"
Issues = "https://github.com/Medicine-Artificial-Intelligence/ProDock/issues"
Documentation = "https://prodock.readthedocs.io/en/latest/"

[tool.hatch.build.targets.wheel]
packages = ["prodock"]
include = [
  "README.md",
  "CHANGELOG.md",
  "LICENSE"
]

[tool.hatch.build.targets.sdist]
include = [
  "prodock",
  "README.md",
  "CHANGELOG.md",
  "LICENSE"
]