# prodock/structure/conversion.py
from __future__ import annotations

"""
Conversion helpers for Meeko, Open Babel, RDKit, and MGLTools.

This module provides two API layers:

1. Backend-specific conversion helpers
   - :func:`convert_with_mekoo`
   - :func:`convert_with_meeko`
   - :func:`convert_with_obabel`

2. Higher-level format conversion helpers
   - :func:`pdb_to_pdbqt`
   - :func:`pdbqt_to_pdb`
   - :func:`sdf_to_pdb`
   - :func:`sdf_to_pdbqt`
   - :func:`ensure_pdbqt`
   - :func:`pdb_to_sdf`
   - :func:`pdbqt_to_sdf`
   - :func:`load_sdf_for_interactions`

Design notes
------------
- PDBQT files generated by Meeko or Open Babel are sanitized unconditionally.
- Receptor validation is available for Open Babel PDBQT receptor generation.
- MGLTools output is supported, but not sanitized here because the sanitizer is
  backend-aware for ``"meeko"`` and ``"obabel"`` only.
- Docked ligand PDBQT files that contain Meeko REMARK metadata can be converted
  to SDF with topology preserved through the Meeko Python API instead of
  Open Babel bond guessing.
- The public name :func:`convert_with_mekoo` is preserved for backward
  compatibility. :func:`convert_with_meeko` is provided as an alias.
"""

import logging
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union

try:
    from rdkit import Chem  # type: ignore

    _RDKIT_AVAILABLE = True
except Exception:
    Chem = None  # type: ignore
    _RDKIT_AVAILABLE = False

try:
    from meeko import PDBQTMolecule, RDKitMolCreate  # type: ignore

    _MEEKO_LIB_AVAILABLE = True
except Exception:
    PDBQTMolecule = None  # type: ignore
    RDKitMolCreate = None  # type: ignore
    _MEEKO_LIB_AVAILABLE = False

from prodock.structure.pdbqt_sanitizer import PDBQTSanitizer

logger = logging.getLogger(__name__)
logger.addHandler(logging.NullHandler())

Backend = Literal["meeko", "obabel", "mgltools"]
PDBQTToSDFBackend = Literal["auto", "meeko", "obabel"]
SanitizeBackend = Literal["meeko", "obabel"]
Mode = Literal["receptor", "ligand"]
TmpConv = Literal["rdkit", "obabel"]

_VINA_RESULT_RE = re.compile(
    r"VINA RESULT:\s*([-+]?\d*\.?\d+)\s+([-+]?\d*\.?\d+)\s+([-+]?\d*\.?\d+)"
)


# ---------------------------------------------------------------------------
# Generic utilities
# ---------------------------------------------------------------------------


def _ensure_exists(path: Union[str, Path], kind: str) -> Path:
    """
    Ensure that a path exists and return its resolved form.

    :param path:
        File path to validate.
    :type path: Union[str, Path]

    :param kind:
        Human-readable label used in error messages.
    :type kind: str

    :returns:
        Resolved existing path.
    :rtype: Path

    :raises FileNotFoundError:
        If the path does not exist.
    """
    p = Path(path).resolve()
    if not p.exists():
        raise FileNotFoundError(f"{kind} not found: {p}")
    return p


def _resolve_executable(command: str) -> Optional[str]:
    """
    Resolve an executable name or explicit path.

    :param command:
        Executable name or filesystem path.
    :type command: str

    :returns:
        Absolute executable path if found, otherwise ``None``.
    :rtype: Optional[str]
    """
    candidate = Path(command)
    if candidate.exists():
        return str(candidate.resolve())
    return shutil.which(command)


def _require_executable(command: str) -> str:
    """
    Require that an executable exists.

    :param command:
        Executable name or explicit path.
    :type command: str

    :returns:
        Resolved executable path.
    :rtype: str

    :raises RuntimeError:
        If the executable cannot be found.
    """
    exe = _resolve_executable(command)
    if exe is None:
        raise RuntimeError(f"Required executable not found: {command}")
    return exe


def _run(args: Sequence[str]) -> subprocess.CompletedProcess:
    """
    Run a subprocess command and raise on failure.

    :param args:
        Command-line argument vector.
    :type args: Sequence[str]

    :returns:
        Completed subprocess result.
    :rtype: subprocess.CompletedProcess

    :raises RuntimeError:
        If the command exits with a non-zero return code.
    """
    proc = subprocess.run(
        list(args),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"Command failed (rc={proc.returncode}): {' '.join(map(str, args))}\n"
            f"STDOUT:\n{proc.stdout}\n"
            f"STDERR:\n{proc.stderr}"
        )
    return proc


def _rdkit_require() -> None:
    """
    Require RDKit availability.

    :returns:
        This function returns nothing.
    :rtype: None

    :raises RuntimeError:
        If RDKit is unavailable.
    """
    if not _RDKIT_AVAILABLE:
        raise RuntimeError("RDKit is required for this operation but is not available.")


def _meeko_lib_require() -> None:
    """
    Require the Meeko Python library.

    :returns:
        This function returns nothing.
    :rtype: None

    :raises RuntimeError:
        If the Meeko Python package is unavailable.
    """
    if not _MEEKO_LIB_AVAILABLE:
        raise RuntimeError(
            "The Meeko Python package is required for this operation but is not available."
        )


def _default_obabel_pdbqt_args(
    extra_args: Optional[Sequence[str]] = None,
) -> List[str]:
    """
    Build Open Babel extra arguments for PDBQT generation.

    If the caller has not already set ``--partialcharge``, Gasteiger charges are
    injected by default.

    :param extra_args:
        Optional user-supplied extra CLI arguments.
    :type extra_args: Optional[Sequence[str]]

    :returns:
        Normalized extra argument list.
    :rtype: List[str]
    """
    args = list(extra_args or [])
    if "--partialcharge" not in args:
        args = ["--partialcharge", "gasteiger"] + args
    return args


def _read_text(path: Union[str, Path]) -> str:
    """
    Read a text file with UTF-8 fallback handling.

    :param path:
        File path to read.
    :type path: Union[str, Path]

    :returns:
        Decoded text content.
    :rtype: str
    """
    return Path(path).read_text(encoding="utf-8", errors="replace")


def _has_meeko_metadata(text: str) -> bool:
    """
    Check whether a PDBQT text block contains Meeko topology metadata.

    :param text:
        File contents to inspect.
    :type text: str

    :returns:
        ``True`` if Meeko REMARK SMILES metadata is present.
    :rtype: bool
    """
    return "REMARK SMILES " in text and "REMARK SMILES IDX " in text


def _parse_vina_pose_records(text: str) -> List[Dict[str, Any]]:
    """
    Parse pose-level Vina metadata from a docked PDBQT text block.

    :param text:
        File contents to inspect.
    :type text: str

    :returns:
        List of pose records containing ``model``, ``affinity``, ``rmsd_lb``,
        and ``rmsd_ub`` when available.
    :rtype: List[Dict[str, Any]]
    """
    records: List[Dict[str, Any]] = []
    current_model: Optional[int] = None

    for raw_line in text.splitlines():
        line = raw_line.strip()

        if line.startswith("MODEL"):
            parts = line.split()
            if len(parts) >= 2:
                try:
                    current_model = int(parts[1])
                except ValueError:
                    current_model = None
            continue

        match = _VINA_RESULT_RE.search(line)
        if match:
            records.append(
                {
                    "model": (
                        current_model if current_model is not None else len(records) + 1
                    ),
                    "affinity": float(match.group(1)),
                    "rmsd_lb": float(match.group(2)),
                    "rmsd_ub": float(match.group(3)),
                }
            )

    return records


def _copy_single_conformer(mol: "Chem.Mol", conf_id: int) -> "Chem.Mol":
    """
    Copy an RDKit molecule while keeping only one conformer.

    :param mol:
        Source molecule.
    :type mol: Chem.Mol

    :param conf_id:
        Conformer index to keep.
    :type conf_id: int

    :returns:
        Copied molecule with a single conformer.
    :rtype: Chem.Mol
    """
    pose_mol = Chem.Mol(mol)  # type: ignore[arg-type]
    conf = Chem.Conformer(mol.GetConformer(conf_id))  # type: ignore[union-attr]
    pose_mol.RemoveAllConformers()  # type: ignore[union-attr]
    pose_mol.AddConformer(conf, assignId=True)  # type: ignore[union-attr]
    return pose_mol


# ---------------------------------------------------------------------------
# PDBQT sanitization and validation
# ---------------------------------------------------------------------------


def _sanitize_pdbqt(
    pdbqt_path: Path,
    *,
    backend: SanitizeBackend,
    rebuild: Optional[bool] = None,
    aggressive: bool = False,
    backup: bool = False,
) -> None:
    """
    Sanitize a produced PDBQT file unconditionally.

    Default rebuild policy depends on the backend:

    - ``"meeko"``  -> ``rebuild=True``
    - ``"obabel"`` -> ``rebuild=False``

    :param pdbqt_path:
        Path to the PDBQT file to sanitize.
    :type pdbqt_path: Path

    :param backend:
        Backend that produced the PDBQT file.
    :type backend: Literal["meeko", "obabel"]

    :param rebuild:
        Whether to rebuild ATOM/HETATM lines into fixed-width PDBQT layout. If
        ``None``, a backend-specific default is used.
    :type rebuild: Optional[bool]

    :param aggressive:
        Whether to enable more aggressive sanitization heuristics.
    :type aggressive: bool

    :param backup:
        Whether to create a backup file before overwriting in place.
    :type backup: bool

    :returns:
        This function returns nothing.
    :rtype: None

    :raises FileNotFoundError:
        If the requested PDBQT file does not exist.
    """
    pdbqt_path = Path(pdbqt_path)
    if not pdbqt_path.exists():
        raise FileNotFoundError(f"PDBQT file does not exist: {pdbqt_path}")

    if rebuild is None:
        rebuild = True if backend == "meeko" else False

    logger.info(
        "Sanitizing %s-produced PDBQT: %s (rebuild=%s, aggressive=%s)",
        backend,
        pdbqt_path,
        rebuild,
        aggressive,
    )
    PDBQTSanitizer.sanitize_file(
        pdbqt_path,
        out_path=None,
        backend=backend,
        rebuild=rebuild,
        aggressive=aggressive,
        backup=backup,
    )


def _contains_atom_records(text: str) -> bool:
    """
    Check whether a text block contains PDB-style atom records.

    :param text:
        File contents to inspect.
    :type text: str

    :returns:
        ``True`` if at least one ``ATOM`` or ``HETATM`` record is present.
    :rtype: bool
    """
    return any(
        line.startswith("ATOM") or line.startswith("HETATM")
        for line in text.splitlines()
    )


def _validate_receptor_pdbqt(
    pdbqt_path: Path,
    *,
    flexible: bool = False,
) -> None:
    """
    Validate that a produced PDBQT matches the requested receptor mode.

    When ``flexible=False``, the file must not contain ligand-style torsion-tree
    markers. When ``flexible=True``, torsion-tree markers are allowed.

    :param pdbqt_path:
        Path to the PDBQT file to validate.
    :type pdbqt_path: Path

    :param flexible:
        Whether the receptor is expected to be flexible.
    :type flexible: bool

    :returns:
        This function returns nothing.
    :rtype: None

    :raises RuntimeError:
        If the file is malformed or inconsistent with the requested receptor
        mode.
    """
    text = Path(pdbqt_path).read_text(encoding="utf-8", errors="replace")

    if not _contains_atom_records(text):
        raise RuntimeError(
            f"Invalid receptor PDBQT: no ATOM/HETATM lines in {pdbqt_path}"
        )

    if not flexible:
        forbidden = (
            "ROOT",
            "BRANCH",
            "ENDBRANCH",
            "ENDROOT",
            "TORSDOF",
            "active torsions",
        )
        text_lower = text.lower()
        for token in forbidden:
            if token.lower() in text_lower:
                raise RuntimeError(
                    f"Invalid rigid receptor PDBQT: found forbidden token '{token}' "
                    f"in {pdbqt_path}. Open Babel likely wrote a flexible PDBQT."
                )


# ---------------------------------------------------------------------------
# Backend-specific helpers
# ---------------------------------------------------------------------------


def convert_with_meeko(
    mekoo_cmd: str,
    input_pdb: Path,
    out_basename: Path,
    write_pdbqt: Optional[Path] = None,
    box_center: Optional[Tuple[float, float, float]] = None,
    box_size: Optional[Tuple[float, float, float]] = None,
    *,
    sanitize_rebuild: Optional[bool] = True,
    sanitize_aggressive: bool = False,
    sanitize_backup: bool = False,
) -> Dict[str, Any]:
    """
    Run a Meeko receptor-preparation command and collect produced artifacts.

    This helper calls ``mk_prepare_receptor.py`` (or a compatible wrapper) to
    generate receptor-preparation outputs. If a PDBQT file is produced, it is
    always sanitized in place.

    :param mekoo_cmd:
        Path or executable name for the Meeko receptor-preparation command.
    :type mekoo_cmd: str

    :param input_pdb:
        Input PDB file passed to Meeko.
    :type input_pdb: Path

    :param out_basename:
        Base output path used by Meeko for generated files, without the final
        extension.
    :type out_basename: Path

    :param write_pdbqt:
        Optional explicit path for a PDBQT output file.
    :type write_pdbqt: Optional[Path]

    :param box_center:
        Optional grid-box center as ``(x, y, z)``.
    :type box_center: Optional[Tuple[float, float, float]]

    :param box_size:
        Optional grid-box size as ``(sx, sy, sz)``.
    :type box_size: Optional[Tuple[float, float, float]]

    :param sanitize_rebuild:
        Whether sanitization should rebuild fixed-width ATOM/HETATM records.
    :type sanitize_rebuild: Optional[bool]

    :param sanitize_aggressive:
        Whether sanitization should use aggressive cleanup heuristics.
    :type sanitize_aggressive: bool

    :param sanitize_backup:
        Whether a backup should be created before in-place sanitization.
    :type sanitize_backup: bool

    :returns:
        Dictionary summarizing command execution. Keys include ``"called"``,
        ``"rc"``, ``"stdout"``, ``"stderr"``, and ``"produced"``.
    :rtype: Dict[str, Any]
    """
    exe = _resolve_executable(mekoo_cmd)

    info: Dict[str, Any] = {
        "called": None,
        "rc": None,
        "stdout": None,
        "stderr": None,
        "produced": [],
    }

    if not exe:
        info["stderr"] = f"Meeko command not found: {mekoo_cmd}"
        logger.warning(info["stderr"])
        return info

    input_pdb = _ensure_exists(input_pdb, "Input PDB")
    out_basename = Path(out_basename)
    if write_pdbqt is not None:
        write_pdbqt = Path(write_pdbqt)

    args: List[str] = [str(exe), "--read_pdb", str(input_pdb), "-o", str(out_basename)]

    if box_center is not None:
        args += [
            "--box_center",
            str(box_center[0]),
            str(box_center[1]),
            str(box_center[2]),
        ]

    if box_size is not None:
        args += [
            "--box_size",
            str(box_size[0]),
            str(box_size[1]),
            str(box_size[2]),
        ]

    if write_pdbqt is not None:
        args += ["--write_pdbqt", str(write_pdbqt)]

    info["called"] = " ".join(args)
    logger.debug("convert_with_mekoo: %s", info["called"])

    try:
        proc = subprocess.run(
            args,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=False,
        )
        info["rc"] = proc.returncode
        info["stdout"] = proc.stdout
        info["stderr"] = proc.stderr
    except Exception as exc:
        info["rc"] = -1
        info["stderr"] = str(exc)
        logger.exception("convert_with_mekoo: invocation failed")
        return info

    produced: List[str] = []

    if write_pdbqt is not None and write_pdbqt.exists():
        _sanitize_pdbqt(
            write_pdbqt,
            backend="meeko",
            rebuild=sanitize_rebuild,
            aggressive=sanitize_aggressive,
            backup=sanitize_backup,
        )
        produced.append(str(write_pdbqt.resolve()))

    for ext in (".pdbqt", ".json"):
        cand = out_basename.with_suffix(ext)
        if cand.exists():
            if ext == ".pdbqt":
                _sanitize_pdbqt(
                    cand,
                    backend="meeko",
                    rebuild=sanitize_rebuild,
                    aggressive=sanitize_aggressive,
                    backup=sanitize_backup,
                )
            resolved = str(cand.resolve())
            if resolved not in produced:
                produced.append(resolved)

    info["produced"] = produced
    logger.debug("convert_with_mekoo: produced=%s", produced)
    return info


convert_with_mekoo = convert_with_meeko


def convert_with_obabel(
    input_path: Path,
    output_path: Path,
    extra_args: Optional[Sequence[str]] = None,
    *,
    sanitize_rebuild: Optional[bool] = False,
    sanitize_aggressive: bool = False,
    sanitize_backup: bool = False,
    validate_receptor: bool = False,
    flexibility: bool = False,
) -> None:
    """
    Convert a structure file with Open Babel and sanitize generated PDBQT output.

    Input and output formats are inferred from file extensions and passed to
    Open Babel using the canonical CLI form:

    .. code-block:: bash

        obabel -i<in_ext> input -o<out_ext> -O output

    When the output format is ``.pdbqt``, the generated file is sanitized in
    place. For receptor preparation, the helper can also validate whether the
    written PDBQT matches the requested rigid or flexible mode.

    :param input_path:
        Input structure file path.
    :type input_path: Path

    :param output_path:
        Output structure file path.
    :type output_path: Path

    :param extra_args:
        Optional extra CLI arguments forwarded to Open Babel.
    :type extra_args: Optional[Sequence[str]]

    :param sanitize_rebuild:
        Whether sanitization should rebuild fixed-width ATOM/HETATM records.
    :type sanitize_rebuild: Optional[bool]

    :param sanitize_aggressive:
        Whether sanitization should use aggressive cleanup heuristics.
    :type sanitize_aggressive: bool

    :param sanitize_backup:
        Whether a backup should be created before in-place sanitization.
    :type sanitize_backup: bool

    :param validate_receptor:
        Whether to validate the generated PDBQT as receptor output.
    :type validate_receptor: bool

    :param flexibility:
        Whether receptor PDBQT output should be generated in flexible mode.
    :type flexibility: bool

    :returns:
        This function returns nothing.
    :rtype: None

    :raises RuntimeError:
        If Open Babel is unavailable, conversion fails, output is missing, or
        receptor validation fails.

    :raises ValueError:
        If the input or output file extension is missing.
    """
    input_path = _ensure_exists(input_path, "Input file")
    output_path = Path(output_path)

    in_ext = input_path.suffix.lower().lstrip(".")
    out_ext = output_path.suffix.lower().lstrip(".")

    if not in_ext:
        raise ValueError(f"Input path has no extension: {input_path}")
    if not out_ext:
        raise ValueError(f"Output path has no extension: {output_path}")

    exe = shutil.which("obabel") or shutil.which("babel")
    if not exe:
        raise RuntimeError("Open Babel (obabel/babel) not found in PATH")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    user_extra_args = list(extra_args or [])

    if out_ext == "pdbqt" and validate_receptor:
        has_x_flag = any(
            isinstance(arg, str) and arg.startswith("-x") for arg in user_extra_args
        )
        if not has_x_flag:
            user_extra_args.append("-xs" if flexibility else "-xrc")

    args = [
        exe,
        f"-i{in_ext}",
        str(input_path),
        f"-o{out_ext}",
        "-O",
        str(output_path),
    ]
    args += user_extra_args

    logger.debug("convert_with_obabel: %s", " ".join(args))
    proc = subprocess.run(
        args,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )

    if proc.returncode != 0:
        logger.error(
            "convert_with_obabel: failed rc=%s stderr=%s",
            proc.returncode,
            proc.stderr,
        )
        raise RuntimeError(f"Open Babel conversion failed: {proc.stderr.strip()}")

    if not output_path.exists():
        raise RuntimeError("Open Babel reported success but output file is missing")

    if output_path.suffix.lower() == ".pdbqt":
        _sanitize_pdbqt(
            output_path,
            backend="obabel",
            rebuild=sanitize_rebuild,
            aggressive=sanitize_aggressive,
            backup=sanitize_backup,
        )

        if validate_receptor:
            _validate_receptor_pdbqt(output_path, flexible=flexibility)

    logger.info("convert_with_obabel: success -> %s", output_path)


# ---------------------------------------------------------------------------
# Internal backend runners used by the higher-level API
# ---------------------------------------------------------------------------


def _meeko_pdb_to_pdbqt(
    input_pdb: Path,
    output_pdbqt: Path,
    *,
    mode: Mode,
    extra_args: Optional[Sequence[str]] = None,
    meeko_cmd: Optional[str] = None,
    sanitize_rebuild: Optional[bool] = None,
    sanitize_aggressive: bool = False,
    sanitize_backup: bool = False,
) -> Path:
    """
    Convert PDB to PDBQT using Meeko.
    """
    input_pdb = _ensure_exists(input_pdb, "Input PDB")
    output_pdbqt = Path(output_pdbqt).resolve()
    output_pdbqt.parent.mkdir(parents=True, exist_ok=True)

    if mode == "receptor":
        exe = _require_executable(meeko_cmd or "mk_prepare_receptor.py")
        args = [
            exe,
            "--read_pdb",
            str(input_pdb),
            "--write_pdbqt",
            str(output_pdbqt),
        ]
    else:
        exe = _require_executable(meeko_cmd or "mk_prepare_ligand.py")
        args = [exe, "-i", str(input_pdb), "-o", str(output_pdbqt)]

    args += list(extra_args or [])
    _run(args)

    if not output_pdbqt.exists():
        raise FileNotFoundError(f"PDBQT not produced: {output_pdbqt}")

    _sanitize_pdbqt(
        output_pdbqt,
        backend="meeko",
        rebuild=sanitize_rebuild,
        aggressive=sanitize_aggressive,
        backup=sanitize_backup,
    )
    return output_pdbqt


def _meeko_sdf_to_pdbqt(
    input_sdf: Path,
    output_pdbqt: Path,
    *,
    extra_args: Optional[Sequence[str]] = None,
    meeko_cmd: Optional[str] = None,
    sanitize_rebuild: Optional[bool] = None,
    sanitize_aggressive: bool = False,
    sanitize_backup: bool = False,
) -> Path:
    """
    Convert SDF to PDBQT using Meeko ligand preparation.
    """
    input_sdf = _ensure_exists(input_sdf, "Input SDF")
    output_pdbqt = Path(output_pdbqt).resolve()
    output_pdbqt.parent.mkdir(parents=True, exist_ok=True)

    exe = _require_executable(meeko_cmd or "mk_prepare_ligand.py")
    args = [exe, "-i", str(input_sdf), "-o", str(output_pdbqt)]
    args += list(extra_args or [])
    _run(args)

    if not output_pdbqt.exists():
        raise FileNotFoundError(f"PDBQT not produced: {output_pdbqt}")

    _sanitize_pdbqt(
        output_pdbqt,
        backend="meeko",
        rebuild=sanitize_rebuild,
        aggressive=sanitize_aggressive,
        backup=sanitize_backup,
    )
    return output_pdbqt


def _meeko_pdbqt_to_sdf(
    input_pdbqt: Path,
    output_sdf: Path,
    *,
    is_dlg: bool = False,
    sanitize: bool = True,
) -> Path:
    """
    Convert a docked ligand PDBQT to SDF using Meeko metadata reconstruction.
    """
    _rdkit_require()
    _meeko_lib_require()

    input_pdbqt = _ensure_exists(input_pdbqt, "Input PDBQT")
    output_sdf = Path(output_sdf).resolve()
    output_sdf.parent.mkdir(parents=True, exist_ok=True)

    text = _read_text(input_pdbqt)
    if not _has_meeko_metadata(text):
        raise ValueError(
            f"{input_pdbqt} does not contain REMARK SMILES / SMILES IDX metadata "
            "required for Meeko-based topology-preserving conversion."
        )

    pdbqt_mol = PDBQTMolecule.from_file(
        str(input_pdbqt),
        is_dlg=is_dlg,
        skip_typing=True,
    )

    rdkit_mols = [
        mol for mol in RDKitMolCreate.from_pdbqt_mol(pdbqt_mol) if mol is not None
    ]
    if not rdkit_mols:
        raise ValueError(
            f"Meeko could not reconstruct any RDKit molecule from {input_pdbqt}"
        )

    pose_records = _parse_vina_pose_records(text)
    writer = Chem.SDWriter(str(output_sdf))  # type: ignore[arg-type]
    if writer is None:
        raise ValueError(f"Could not open SDF writer for {output_sdf}")

    try:
        for part_index, mol in enumerate(rdkit_mols, start=1):
            n_confs = mol.GetNumConformers()  # type: ignore[union-attr]
            if n_confs == 0:
                pose_mol = Chem.Mol(mol)  # type: ignore[arg-type]
                if sanitize:
                    Chem.SanitizeMol(pose_mol)  # type: ignore[arg-type]
                writer.write(pose_mol)
                continue

            for conf_id in range(n_confs):
                pose_mol = _copy_single_conformer(mol, conf_id)
                record = pose_records[conf_id] if conf_id < len(pose_records) else {}
                pose_rank = int(record.get("model", conf_id + 1))

                name = input_pdbqt.stem
                if len(rdkit_mols) > 1:
                    name = f"{name}__part{part_index}"

                pose_mol.SetProp("_Name", f"{name}__pose{pose_rank}")  # type: ignore[union-attr]
                pose_mol.SetProp("source_file", str(input_pdbqt))  # type: ignore[union-attr]
                pose_mol.SetIntProp("pose_rank", pose_rank)  # type: ignore[union-attr]

                if "affinity" in record:
                    pose_mol.SetDoubleProp("affinity", float(record["affinity"]))  # type: ignore[union-attr]
                if "rmsd_lb" in record:
                    pose_mol.SetDoubleProp("rmsd_lb", float(record["rmsd_lb"]))  # type: ignore[union-attr]
                if "rmsd_ub" in record:
                    pose_mol.SetDoubleProp("rmsd_ub", float(record["rmsd_ub"]))  # type: ignore[union-attr]

                if sanitize:
                    Chem.SanitizeMol(pose_mol)  # type: ignore[arg-type]

                writer.write(pose_mol)
    finally:
        writer.close()

    return output_sdf


def _mgltools_pdb_to_pdbqt(
    input_pdb: Path,
    output_pdbqt: Path,
    *,
    mode: Mode,
    extra_args: Optional[Sequence[str]] = None,
    mgltools_cmd: Optional[str] = None,
) -> Path:
    """
    Convert PDB to PDBQT using MGLTools.
    """
    input_pdb = _ensure_exists(input_pdb, "Input PDB")
    output_pdbqt = Path(output_pdbqt).resolve()
    output_pdbqt.parent.mkdir(parents=True, exist_ok=True)

    if mode == "receptor":
        exe = _require_executable(mgltools_cmd or "prepare_receptor4.py")
        args = [exe, "-r", str(input_pdb), "-o", str(output_pdbqt)]
    else:
        exe = _require_executable(mgltools_cmd or "prepare_ligand4.py")
        args = [exe, "-l", str(input_pdb), "-o", str(output_pdbqt)]

    args += list(extra_args or [])
    _run(args)

    if not output_pdbqt.exists():
        raise FileNotFoundError(f"PDBQT not produced: {output_pdbqt}")

    logger.info(
        "MGLTools produced PDBQT without sanitizer pass: %s",
        output_pdbqt,
    )
    return output_pdbqt


def _mgltools_sdf_to_pdbqt(
    input_sdf: Path,
    output_pdbqt: Path,
    *,
    extra_args: Optional[Sequence[str]] = None,
    mgltools_cmd: Optional[str] = None,
) -> Path:
    """
    Convert SDF to PDBQT using MGLTools ligand preparation.
    """
    input_sdf = _ensure_exists(input_sdf, "Input SDF")
    output_pdbqt = Path(output_pdbqt).resolve()
    output_pdbqt.parent.mkdir(parents=True, exist_ok=True)

    exe = _require_executable(mgltools_cmd or "prepare_ligand4.py")
    args = [exe, "-l", str(input_sdf), "-o", str(output_pdbqt)]
    args += list(extra_args or [])
    _run(args)

    if not output_pdbqt.exists():
        raise FileNotFoundError(f"PDBQT not produced: {output_pdbqt}")

    logger.info(
        "MGLTools produced PDBQT without sanitizer pass: %s",
        output_pdbqt,
    )
    return output_pdbqt


# ---------------------------------------------------------------------------
# Interaction-focused SDF loading
# ---------------------------------------------------------------------------


def load_sdf_for_interactions(
    sdf_path: Union[str, Path],
    *,
    sanitize: bool = True,
    remove_hs: bool = False,
    strict_parsing: bool = False,
    resname: str = "LIG",
    resnumber: int = 1,
    chain: str = "",
) -> Any:
    """
    Load the first valid ligand molecule from an SDF for interaction analysis.

    This helper is intended for the common ProDock interaction workflow where
    a temporary SDF already corresponds to a single pose. It applies a relaxed
    fallback strategy if strict RDKit sanitization fails and restores minimal
    residue metadata required by downstream ProLIF conversion.

    :param sdf_path:
        Input SDF path.
    :type sdf_path: Union[str, Path]

    :param sanitize:
        Whether to sanitize on the first RDKit load attempt.
    :type sanitize: bool

    :param remove_hs:
        Whether RDKit should remove hydrogens during load.
    :type remove_hs: bool

    :param strict_parsing:
        Whether RDKit strict parsing should be enabled.
    :type strict_parsing: bool

    :param resname:
        Default residue name to attach if missing.
    :type resname: str

    :param resnumber:
        Default residue number to attach if missing.
    :type resnumber: int

    :param chain:
        Default chain identifier to attach if missing.
    :type chain: str

    :returns:
        First valid RDKit molecule from the SDF.
    :rtype: Any

    :raises ValueError:
        If no valid molecule can be loaded.
    """
    _rdkit_require()
    sdf_path = _ensure_exists(sdf_path, "Input SDF")

    attempts = [
        {
            "sanitize": sanitize,
            "removeHs": remove_hs,
            "strictParsing": strict_parsing,
        }
    ]

    if sanitize:
        attempts.append(
            {
                "sanitize": False,
                "removeHs": remove_hs,
                "strictParsing": strict_parsing,
            }
        )

    last_error: Optional[Exception] = None

    for kwargs in attempts:
        try:
            supplier = Chem.SDMolSupplier(str(sdf_path), **kwargs)  # type: ignore[arg-type]
            mol = next((m for m in supplier if m is not None), None)
            if mol is None:
                continue

            try:
                if not mol.HasProp("_Name") or not str(mol.GetProp("_Name")).strip():
                    mol.SetProp("_Name", Path(sdf_path).stem)
            except Exception:
                pass

            try:
                if not mol.HasProp("mol_name"):
                    mol.SetProp("mol_name", mol.GetProp("_Name"))
            except Exception:
                pass

            try:
                if not mol.HasProp("resname"):
                    mol.SetProp("resname", str(resname))
                if not mol.HasProp("chain"):
                    mol.SetProp("chain", str(chain))
                if not mol.HasProp("resnumber"):
                    mol.SetIntProp("resnumber", int(resnumber))
            except Exception:
                pass

            return mol

        except Exception as exc:
            last_error = exc

    if last_error is not None:
        raise ValueError(f"No valid molecule found in SDF: {sdf_path}") from last_error
    raise ValueError(f"No valid molecule found in SDF: {sdf_path}")


# ---------------------------------------------------------------------------
# General structure conversions
# ---------------------------------------------------------------------------


def pdb_to_pdbqt(
    input_pdb: Union[str, Path],
    output_pdbqt: Union[str, Path],
    *,
    mode: Mode,
    backend: Backend,
    extra_args: Optional[Sequence[str]] = None,
    meeko_cmd: Optional[str] = None,
    mgltools_cmd: Optional[str] = None,
    sanitize_rebuild: Optional[bool] = None,
    sanitize_aggressive: bool = False,
    sanitize_backup: bool = False,
    validate_receptor: Optional[bool] = None,
    flexibility: bool = False,
) -> Path:
    """
    Convert PDB to PDBQT using a single explicit backend.
    """
    input_pdb = _ensure_exists(input_pdb, "Input PDB")
    output_pdbqt = Path(output_pdbqt).resolve()
    output_pdbqt.parent.mkdir(parents=True, exist_ok=True)

    if validate_receptor is None:
        validate_receptor = mode == "receptor"

    if backend == "meeko":
        return _meeko_pdb_to_pdbqt(
            input_pdb,
            output_pdbqt,
            mode=mode,
            extra_args=extra_args,
            meeko_cmd=meeko_cmd,
            sanitize_rebuild=sanitize_rebuild,
            sanitize_aggressive=sanitize_aggressive,
            sanitize_backup=sanitize_backup,
        )

    if backend == "obabel":
        convert_with_obabel(
            input_pdb,
            output_pdbqt,
            extra_args=_default_obabel_pdbqt_args(extra_args),
            sanitize_rebuild=sanitize_rebuild,
            sanitize_aggressive=sanitize_aggressive,
            sanitize_backup=sanitize_backup,
            validate_receptor=validate_receptor,
            flexibility=flexibility,
        )
        return output_pdbqt

    if backend == "mgltools":
        return _mgltools_pdb_to_pdbqt(
            input_pdb,
            output_pdbqt,
            mode=mode,
            extra_args=extra_args,
            mgltools_cmd=mgltools_cmd,
        )

    raise ValueError("backend must be one of: 'meeko', 'obabel', 'mgltools'.")


def pdbqt_to_pdb(
    input_pdbqt: Union[str, Path],
    output_pdb: Union[str, Path],
    *,
    backend: Literal["obabel"],
    extra_args: Optional[Sequence[str]] = None,
) -> Path:
    """
    Convert PDBQT to PDB using Open Babel.
    """
    if backend != "obabel":
        raise NotImplementedError(
            "PDBQT -> PDB is only supported with backend='obabel'."
        )

    input_pdbqt = _ensure_exists(input_pdbqt, "Input PDBQT")
    output_pdb = Path(output_pdb).resolve()
    output_pdb.parent.mkdir(parents=True, exist_ok=True)

    convert_with_obabel(
        input_pdbqt,
        output_pdb,
        extra_args=extra_args,
        validate_receptor=False,
    )

    if not output_pdb.exists():
        raise FileNotFoundError(f"PDB not produced: {output_pdb}")

    return output_pdb


def sdf_to_pdb(
    input_sdf: Union[str, Path],
    output_pdb: Union[str, Path],
    *,
    backend: Literal["rdkit", "obabel"],
    extra_args: Optional[Sequence[str]] = None,
) -> Path:
    """
    Convert SDF to PDB using a single explicit backend.
    """
    input_sdf = _ensure_exists(input_sdf, "Input SDF")
    output_pdb = Path(output_pdb).resolve()
    output_pdb.parent.mkdir(parents=True, exist_ok=True)

    if backend == "rdkit":
        _rdkit_require()
        suppl = Chem.SDMolSupplier(str(input_sdf), removeHs=False, sanitize=True)  # type: ignore[arg-type]
        mol = next((m for m in suppl if m is not None), None)
        if mol is None:
            raise ValueError(f"No valid molecule found in {input_sdf}")
        Chem.MolToPDBFile(mol, str(output_pdb))  # type: ignore[arg-type]

    elif backend == "obabel":
        convert_with_obabel(
            input_sdf,
            output_pdb,
            extra_args=extra_args,
            validate_receptor=False,
        )

    else:
        raise ValueError("backend must be 'rdkit' or 'obabel'.")

    if not output_pdb.exists():
        raise FileNotFoundError(f"PDB not produced: {output_pdb}")

    return output_pdb


def sdf_to_pdbqt(
    input_sdf: Union[str, Path],
    output_pdbqt: Union[str, Path],
    *,
    backend: Backend,
    tmp_from_sdf_backend: TmpConv = "rdkit",
    extra_args: Optional[Sequence[str]] = None,
    meeko_cmd: Optional[str] = None,
    mgltools_cmd: Optional[str] = None,
    sanitize_rebuild: Optional[bool] = None,
    sanitize_aggressive: bool = False,
    sanitize_backup: bool = False,
) -> Path:
    """
    Convert SDF to PDBQT using a single explicit backend.
    """
    _ = tmp_from_sdf_backend
    input_sdf = _ensure_exists(input_sdf, "Input SDF")
    output_pdbqt = Path(output_pdbqt).resolve()
    output_pdbqt.parent.mkdir(parents=True, exist_ok=True)

    if backend == "meeko":
        return _meeko_sdf_to_pdbqt(
            input_sdf,
            output_pdbqt,
            extra_args=extra_args,
            meeko_cmd=meeko_cmd,
            sanitize_rebuild=sanitize_rebuild,
            sanitize_aggressive=sanitize_aggressive,
            sanitize_backup=sanitize_backup,
        )

    if backend == "obabel":
        convert_with_obabel(
            input_sdf,
            output_pdbqt,
            extra_args=_default_obabel_pdbqt_args(extra_args),
            sanitize_rebuild=sanitize_rebuild,
            sanitize_aggressive=sanitize_aggressive,
            sanitize_backup=sanitize_backup,
            validate_receptor=False,
        )
        return output_pdbqt

    if backend == "mgltools":
        return _mgltools_sdf_to_pdbqt(
            input_sdf,
            output_pdbqt,
            extra_args=extra_args,
            mgltools_cmd=mgltools_cmd,
        )

    raise ValueError("backend must be one of: 'meeko', 'obabel', 'mgltools'.")


def ensure_pdbqt(
    input_path: Union[str, Path],
    output_dir: Union[str, Path],
    *,
    backend: Backend,
    mode: Mode = "ligand",
    tmp_from_sdf_backend: TmpConv = "rdkit",
    extra_args: Optional[Sequence[str]] = None,
    meeko_cmd: Optional[str] = None,
    mgltools_cmd: Optional[str] = None,
    sanitize_rebuild: Optional[bool] = None,
    sanitize_aggressive: bool = False,
    sanitize_backup: bool = False,
    validate_receptor: Optional[bool] = None,
    flexibility: bool = False,
) -> Path:
    """
    Ensure that an input file is available as PDBQT using the chosen backend.
    """
    _ = tmp_from_sdf_backend
    p = _ensure_exists(input_path, "Input")
    out_dir = Path(output_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    ext = p.suffix.lower()
    out_p = out_dir / f"{p.stem}.pdbqt"

    if ext == ".pdbqt":
        return p

    if ext == ".pdb":
        return pdb_to_pdbqt(
            p,
            out_p,
            mode=mode,
            backend=backend,
            extra_args=extra_args,
            meeko_cmd=meeko_cmd,
            mgltools_cmd=mgltools_cmd,
            sanitize_rebuild=sanitize_rebuild,
            sanitize_aggressive=sanitize_aggressive,
            sanitize_backup=sanitize_backup,
            validate_receptor=validate_receptor,
            flexibility=flexibility,
        )

    if ext == ".sdf":
        return sdf_to_pdbqt(
            p,
            out_p,
            backend=backend,
            tmp_from_sdf_backend=tmp_from_sdf_backend,
            extra_args=extra_args,
            meeko_cmd=meeko_cmd,
            mgltools_cmd=mgltools_cmd,
            sanitize_rebuild=sanitize_rebuild,
            sanitize_aggressive=sanitize_aggressive,
            sanitize_backup=sanitize_backup,
        )

    if ext in {".mol2", ".smi"}:
        if backend != "obabel":
            raise NotImplementedError(
                f"Input extension {ext} to PDBQT is only supported with backend='obabel'."
            )

        convert_with_obabel(
            p,
            out_p,
            extra_args=_default_obabel_pdbqt_args(extra_args),
            sanitize_rebuild=sanitize_rebuild,
            sanitize_aggressive=sanitize_aggressive,
            sanitize_backup=sanitize_backup,
            validate_receptor=(
                (mode == "receptor") if validate_receptor is None else validate_receptor
            ),
            flexibility=flexibility,
        )

        if not out_p.exists():
            raise FileNotFoundError(f"PDBQT not produced: {out_p}")
        return out_p

    raise NotImplementedError(
        f"Unsupported input extension {ext} for ensure_pdbqt with backend='{backend}'."
    )


def pdb_to_sdf(
    input_pdb: Union[str, Path],
    output_sdf: Union[str, Path],
    *,
    backend: Literal["rdkit", "obabel"],
    extra_args: Optional[Sequence[str]] = None,
) -> Path:
    """
    Convert PDB to SDF using a single explicit backend.
    """
    input_pdb = _ensure_exists(input_pdb, "Input PDB")
    output_sdf = Path(output_sdf).resolve()
    output_sdf.parent.mkdir(parents=True, exist_ok=True)

    if backend == "rdkit":
        _rdkit_require()
        mol = Chem.MolFromPDBFile(str(input_pdb), removeHs=False)  # type: ignore[arg-type]
        if mol is None:
            raise ValueError(f"RDKit could not parse PDB: {input_pdb}")
        writer = Chem.SDWriter(str(output_sdf))  # type: ignore[arg-type]
        writer.write(mol)
        writer.close()

    elif backend == "obabel":
        convert_with_obabel(
            input_pdb,
            output_sdf,
            extra_args=extra_args,
            validate_receptor=False,
        )

    else:
        raise ValueError("backend must be 'rdkit' or 'obabel'.")

    if not output_sdf.exists():
        raise FileNotFoundError(f"SDF not produced: {output_sdf}")

    return output_sdf


def pdbqt_to_sdf(
    input_pdbqt: Union[str, Path],
    output_sdf: Union[str, Path],
    *,
    backend: PDBQTToSDFBackend = "auto",
    extra_args: Optional[Sequence[str]] = None,
    is_dlg: bool = False,
    sanitize: bool = True,
) -> Path:
    """
    Convert PDBQT to SDF.
    """
    input_pdbqt = _ensure_exists(input_pdbqt, "Input PDBQT")
    output_sdf = Path(output_sdf).resolve()
    output_sdf.parent.mkdir(parents=True, exist_ok=True)

    text = _read_text(input_pdbqt)
    has_metadata = _has_meeko_metadata(text)

    if backend == "auto":
        if has_metadata:
            return _meeko_pdbqt_to_sdf(
                input_pdbqt,
                output_sdf,
                is_dlg=is_dlg,
                sanitize=sanitize,
            )
        convert_with_obabel(
            input_pdbqt,
            output_sdf,
            extra_args=extra_args,
            validate_receptor=False,
        )

    elif backend == "meeko":
        return _meeko_pdbqt_to_sdf(
            input_pdbqt,
            output_sdf,
            is_dlg=is_dlg,
            sanitize=sanitize,
        )

    elif backend == "obabel":
        convert_with_obabel(
            input_pdbqt,
            output_sdf,
            extra_args=extra_args,
            validate_receptor=False,
        )

    else:
        raise ValueError("backend must be one of: 'auto', 'meeko', 'obabel'.")

    if not output_sdf.exists():
        raise FileNotFoundError(f"SDF not produced: {output_sdf}")

    return output_sdf


__all__ = [
    "Backend",
    "Mode",
    "PDBQTToSDFBackend",
    "SanitizeBackend",
    "TmpConv",
    "convert_with_mekoo",
    "convert_with_meeko",
    "convert_with_obabel",
    "pdb_to_pdbqt",
    "pdbqt_to_pdb",
    "sdf_to_pdb",
    "sdf_to_pdbqt",
    "ensure_pdbqt",
    "pdb_to_sdf",
    "pdbqt_to_sdf",
    "load_sdf_for_interactions",
]
