name: Publish to Anaconda (conda)

on:
  release:
    types: [published]
  push:
    branches: [conda]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          auto-update-conda: true
          auto-activate-base: true

      - name: Create build environment (conda-build + anaconda-client)
        run: |
          # ensure conda functions are available for this shell
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda create -n build -y -c conda-forge python=3.11 "conda-build>=3.21" anaconda-client
          conda activate build
          conda info --envs

      - name: Build conda package(s)
        run: |
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate build
          rm -rf conda-bld || true
          mkdir -p conda-bld

          if [ -d recipe ]; then
            conda-build recipe --output-folder ./conda-bld
          else
            conda-build . --output-folder ./conda-bld
          fi

          echo "Built files:"
          find conda-bld -type f \( -name "*.conda" -o -name "*.tar.bz2" \) -print

      - name: Upload built packages as artifact
        uses: actions/upload-artifact@v4
        with:
          name: conda-packages
          path: conda-bld/

  publish_release:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          name: conda-packages
          path: conda-bld

      - name: Install/upgrade Anaconda client
        run: python3 -m pip install --upgrade anaconda-client

      - name: Upload packages to Anaconda.org (main)
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          set -euo pipefail
          if [ -z "${ANACONDA_TOKEN:-}" ]; then
            echo "ANACONDA_TOKEN is not set"; exit 1
          fi

          # find packages and upload, robust for filenames with spaces/newlines
          find conda-bld -type f \( -name "*.conda" -o -name "*.tar.bz2" \) -print0 | \
            while IFS= read -r -d '' pkg; do
              echo "Uploading: $pkg"
              anaconda -t "${ANACONDA_TOKEN}" upload --user tieulongphan --label main --no-progress "$pkg"
            done

  publish_beta:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/conda'
    runs-on: ubuntu-latest
    steps:
      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          name: conda-packages
          path: conda-bld

      - name: Install/upgrade Anaconda client
        run: python3 -m pip install --upgrade anaconda-client

      - name: Upload packages to Anaconda.org (beta)
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          set -euo pipefail
          if [ -z "${ANACONDA_TOKEN:-}" ]; then
            echo "ANACONDA_TOKEN is not set"; exit 1
          fi

          find conda-bld -type f \( -name "*.conda" -o -name "*.tar.bz2" \) -print0 | \
            while IFS= read -r -d '' pkg; do
              echo "Uploading: $pkg"
              anaconda -t "${ANACONDA_TOKEN}" upload --user tieulongphan --label beta --no-progress "$pkg"
            done
